all done, except a report.

diff --git a/Final/Makefile b/Final/Makefile
--- a/Final/Makefile
+++ b/Final/Makefile
@@ -1,70 +1,64 @@
-RM       = rm -rf
-MAKEFLAGS = --no-print-directory
-
-.PHONY: build clean rebuild handin
+.PHONY: build clean handin compile run run-one
 
 BUILD_DIR = $(CURDIR)/build
 
 build:
 	@cmake -G Ninja -B $(BUILD_DIR) -DCMAKE_BUILD_TYPE=Release; \
 	cd $(BUILD_DIR) && ninja
-# cd $(BUILD_DIR) && ninja -v
 
 clean: 
 	@$(RM) build ; \
-	$(RM) test/HW3/*.4.quad test/HW4/*.4.quad test/Other/*.4.quad ; \
-
-rebuild: clean build
+	cd $(CURDIR)/test && \
+    for file in $$(ls .); do \
+        if [ "$${file##*.}" != "fmj" ]; then \
+            echo "Removing $$file"; \
+            rm -f "$$file"; \
+        fi; \
+    done; \
+    cd .. > /dev/null 2>&1
 
 handin:
 	@if [ ! -f docs/report.pdf ]; then \
 		echo "请先在docs文件夹下攥写报告, 并转换为'report.pdf'"; \
 		exit 1; \
 	fi; \
-	filename="22300240008-曹奕伦"; \
-	zip -q -r "docs/$$filename-hw5.zip" \
-	  docs/report.pdf include lib
-
-.PHONY: run run-one
+	filename="22307110206-胥昊天"; \
+	zip -q -r "docs/$$filename-final.zip" \
+	  docs/report.pdf include lib 
 
 MAIN = $(BUILD_DIR)/tools/main/main
-PATCHDEMO = $(BUILD_DIR)/tools/patchdemo/patchdemo
 
-run: $(MAIN)
+compile: build
 	cd $(CURDIR)/test && \
 	for file in $$(ls .); do \
         if [ "$${file##*.}" = "fmj" ]; then \
-            echo "Reading $${file%%.*}"; \
+            echo "Compiling $${file}"; \
 			$(MAIN) "$${file%%.*}"; \
+			arm-linux-gnueabihf-gcc -mcpu=cortex-a72 -Wall -Wextra --static -o "$${file%%.*}" "$${file%%.*}.4.s" ../vendor/libsysy/libsysy32.s -lm; \
         fi \
 	done; \
-	cd .. > /dev/null 2>&1 
-
-define run_test
-	cd $(CURDIR)/test/$(1) && \
-	for file in $$(ls .); do \
-		if [ "$${file#*.}" = "4-xml.quad" ]; then \
-			echo "Reading $${file}"; \
-			$(MAIN) "$${file%%.*}"; \
-		fi; \
-	done; \
 	cd .. > /dev/null 2>&1
-endef
 
-# run: $(MAIN)
-# 	$(call run_test, HW3)
-# 	$(call run_test,HW4)
-# 	$(call run_test,Other)
-
-run-assem: $(MAIN)
+run: compile
 	cd $(CURDIR)/test && \
 	for file in $$(ls .); do \
 		if [ "$${file##*.}" = "s" ]; then \
-			echo "Processing assembly file: $$file"; \
-			echo "Compiling $${file}"; \
-			arm-linux-gnueabihf-gcc -mcpu=cortex-a72 -Wall -Wextra --static -o "$${file%%.*}" "$$file" ../vendor/libsysy/libsysy32.s -lm; \
-			echo "Running the final assembly program........."; \
+			echo "Running the program $${file} ........."; \
 			qemu-arm -B 0x1000 "$${file%%.*}"; \
 		fi; \
 	done; \
-	cd .. > /dev/null 2>&1 
+	cd .. > /dev/null 2>&1
+
+run-one: compile
+	@if [ -z "$(PROG)" ]; then \
+		echo "Usage: make run-one PROG=<program_name> (e.g., make run-one PROG=hw10test00)"; \
+		exit 1; \
+	fi
+	@cd $(CURDIR)/test && \
+	if [ -f "$(PROG)" ]; then \
+		echo "Running $(PROG) ..."; \
+		qemu-arm -B 0x1000 "$(PROG)" || true; \
+	else \
+		echo "Error: $(PROG) not found in test directory."; \
+		exit 1; \
+	fi
